spring.application.name=SpringSecurtiy_Login_Registration

spring.datasource.url=jdbc:mysql://localhost:3306/sbms
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.allow-circular-references=true
